//Book Actions
export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_FAILURE = "UPDATE_BOOK_FAILURE";
export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";
export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE";

export const FETCH_AUTHORS_REQUEST="FETCH_AUTHORS_REQUEST";
export const FETCH_AUTHORS_SUCCESS="FETCH_AUTHORS_SUCCESS";
export const FETCH_AUTHORS_FAILURE="FETCH_AUTHORS_FAILURE";
export const UPDATE_AUTHOR_REQUEST="UPDATE_AUTHOR_REQUEST";
export const UPDATE_AUTHOR_SUCCESS="UPDATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_FAILURE="UPDATE_AUTHOR_FAILURE";
export const DELETE_AUTHOR_REQUEST="DELETE_AUTHOR_REQUEST";
export const DELETE_AUTHOR_SUCCESS="DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAILURE="DELETE_AUTHOR_FAILURE";
export const CREATE_AUTHOR_REQUEST="CREATE_AUTHOR_REQUEST";
export const CREATE_AUTHOR_SUCCESS="CREATE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_FAILURE="CREATE_AUTHOR_FAILURE";